-- Credentials Confirmer
DROP PROCEDURE IF EXISTS `SP_CONFIRM_ADMIN_KEY`;
DELIMITER //
CREATE DEFINER='n3G49MRq9MIh'@'localhost' PROCEDURE `SP_CONFIRM_ADMIN_KEY`(IN `cs` BINARY(16), OUT `VALID` BOOLEAN)
BEGIN
	SELECT @ADMIN_KEY:=AES_DECRYPT(`cs`, @admin_key);
    IF ADMIN_KEY = BINARY('fl13O3QW98Iikn0') THEN
        SET `VALID` = TRUE;
	ELSE 
		SET `VALID` = FALSE;
	END IF;
END //
DELIMITER ;

-- Get all users
DELIMITER //
CREATE PROCEDURE `sp_getAllUsers`()
BEGIN
	SELECT * FROM `USERS`;
END //
DELIMITER ;