-- Users
DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS`(
	`id` BINARY(16) NOT NULL,
    `username` VARCHAR(16) NOT NULL,
    `password` CHAR(72) NOT NULL,
    `email` VARCHAR(64) NOT NULL,
    `role` TINYINT NOT NULL,
    `active` BOOLEAN DEFAULT TRUE,
    CONSTRAINT `US_KEY` PRIMARY KEY (`id`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `SALES`;
CREATE TABLE `SALES`(
	`id` BINARY(16) NOT NULL,
    `US_id` BINARY(16) NOT NULL,
    `SH_id` BINARY(16) NOT NULL,
    `ST_id` BINARY(16) NOT NULL,
    `HL_id` BINARY(16) NOT NULL,
    `price` DECIMAL(5,2) NOT NULL,
    `date` DATETIME NOT NULL,
    `active` BOOLEAN DEFAULT TRUE,
    CONSTRAINT `SL_KEY` PRIMARY KEY(`id`)
) ENGINE = InnoDB CHARACTER SET utf8mb4;

CREATE TABLE `MOVIES`(
    `id` BINARY(16) NOT NULL,
    `description` VARCHAR(256) NOT NULL,
    `title` VARCHAR(48) NOT NULL,
    `year` YEAR NOT NULL,
    `subtitles` BOOLEAN NOT NULL,
    `rating` INT NOT NULL,
    `length` INT NOT NULL,
    `country` CHAR(3) NOT NULL,
    CONSTRAINT `MV_KEY` PRIMARY KEY(`id`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `SCORES`;
CREATE TABLE `SCORES`(
    `id` BINARY(16) NOT NULL,
    `MV_id` BINARY(16) NOT NULL,
    `score` DECIMAL(2,1) NOT NULL,
    `US_id` BINARY(16) NOT NULL,
    CONSTRAINT `SC_KEY` PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE `GENRES`(
    `id` BINARY(16) NOT NULL,
    `name` VARCHAR(6) NOT NULL,
    CONSTRAINT `GR_KEY` PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE `PEOPLE`(
    `id` BINARY(16) NOT NULL,
    `name` VARCHAR(32) NOT NULL,
    CONSTRAINT `PP_KEY` PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE `COMPANIES`(
    `id` BINARY(16) NOT NULL,
    `name` VARCHAR(32) NOT NULL,
    CONSTRAINT `CY_KEY` PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE `SHOWINGS`(
    `id` BINARY(16) NOT NULL,
    `start` DATETIME NOT NULL,
    `end` DATETIME NOT NULL,
    `MV_id` BINARY(16) NOT NULL,
    `hall` TINYINT NOT NULL,
    CONSTRAINT `FC_KEY` PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE `SEATS`(
    `id` BINARY(16) NOT NULL,
    `SH_id` BINARY(16) NOT NULL,
    `row` INT NOT NULL,
    `slot` INT NOT NULL,
    `status` VARCHAR(8) NOT NULL,
    CONSTRAINT `PK_SEAT` PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE `MOVIE_HAS_GENRE`(
	`MV_id` BINARY(16) NOT NULL,
    `GR_id` BINARY(16) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8mb4;

CREATE TABLE `PERSON_HAS_ROLE`(
	`MV_id` BINARY(16) NOT NULL,
    `PP_id` BINARY(16),
    `role` CHAR(3) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8mb4;

CREATE TABLE `COMPANY_HAS_ROLE`(
	`MV_id` BINARY(16) NOT NULL,
    `CY_id` BINARY(16) NOT NULL,
    `role` CHAR(3) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8mb4;
-- END TABLES

-- Key Chain
DROP TABLE IF EXISTS `keychain`;
CREATE TABLE `keychain`(
	`name` VARCHAR(9) NOT NULL,
    `key` VARCHAR(32) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8mb4;